apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jc04xrrua-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jc04xrrua-python 
  name: jc04xrrua-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jc04xrrua-python 
